// tableau des mots 

let listMots = [
    "arbre", "soleil", "montagne", "rivière", "plage", "forêt", "château", "oiseau", "nuage", "vent",
    "étoile", "lune", "fleur", "papillon", "pluie", "neige", "feuille", "pont", "chemin", "lac",
    "océan", "sable", "tempête", "tornade", "cascade", "île", "volcan", "glacier", "grottes", "prairie",
    "vallée", "désert", "clairière", "roseau", "sapin", "érable", "cactus", "bambou", "marécage", "falaise",
    "corail", "cristal", "grotte", "liane", "baie", "ouragan", "canyon", "givre", "toundra", "delta"
  ];
let listPhrase = [
    "Brazza la belle ville",
    "Le soleil brille dans le ciel.",
    "La mer est d'un bleu profond.",
    "Les oiseaux chantent au lever du jour.",
    "Un vent léger souffle sur la plaine.",
    "Les montagnes sont couvertes de neige.",
    "Un chat noir traverse la rue.",
    "L'horloge sonne midi.",
    "Un enfant joue dans le jardin.",
    "Les feuilles tombent en automne.",
    "Le café sent bon le matin.",
    "Un chien aboie au loin.",
    "Les étoiles brillent dans la nuit.",
    "Un avion traverse le ciel.",
    "La pluie tambourine sur la fenêtre.",
    "Le vent fait danser les arbres.",
    "Les vagues s'écrasent sur la plage.",
    "Un feu crépite dans la cheminée.",
    "Le parfum des fleurs embaume l'air.",
    "Un papillon vole de fleur en fleur.",
    "Les enfants rient et courent dans le parc.",
    "Le silence règne dans la forêt.",
    "Les nuages cachent le soleil.",
    "Un arc-en-ciel apparaît après l'orage.",
    "Le chat ronronne sur le canapé.",
    "Un livre ouvert repose sur la table.",
    "Le train entre en gare.",
    "Un musicien joue dans la rue.",
    "Les lumières de la ville scintillent la nuit.",
    "Une horloge ancienne marque l'heure.",
    "Le son des vagues est apaisant.",
    "Les enfants construisent un château de sable.",
    "Le vent souffle dans les voiles du bateau.",
    "Les cloches de l'église résonnent au loin.",
    "Un écrivain note ses idées dans un carnet.",
    "Un écureuil grimpe à l'arbre.",
    "Le son d'un violon remplit la pièce.",
    "Un train traverse la campagne.",
    "Un chien court après une balle.",
    "Les étoiles filantes traversent le ciel.",
    "Une brise douce caresse le visage.",
    "Les vagues roulent sur les rochers.",
    "Un hibou hulule dans la nuit.",
    "Une bougie éclaire doucement la pièce.",
    "Les rues s'illuminent pour les fêtes.",
    "Un cheval galope dans la prairie.",
    "Un enfant apprend à faire du vélo.",
    "Le parfum du pain chaud remplit la boulangerie.",
    "Un pêcheur attend patiemment au bord du lac.",
    "Les lucioles brillent dans l'obscurité."
];


